spring:
  application:
    name: tea-app-back-end
  datasource:
    url: jdbc:h2:mem:security-security
    driverClassName: org.h2.Driver
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  token:
    signing:
      key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
  mail:
    host: smtp.yandex.ru
    username: test.email.for.project@yandex.ru
    password: roopwphfbttsymad
    port: 465
    protocol: smtps
    debug: false

logging:
  level:
    org.example.teaappbackend.gateway.controllers: debug
    org.example.teaappbackend.gateway.services: debug
    sql: debug
    org.hibernate.SQL: debug
    org.hibernate.org.hibernate.type: trace

application:
  constants:
    ttl-auth-code-in-sec: 1000
